<h3>Processing</h3>
Please wait as we confirm the status of your order
<script>
require(['jquery', 'loader', 'domReady!'], function ($) {
    'use strict';
    $('body').loader({ icon: "<?php echo $this->getViewFileUrl('images/loader-2.gif'); ?>"});
    $('body').loader('show');
    $('body').trigger('processStart');
    let redirectUrl = "<?php echo $block->getBaseUrl(); ?>"+"/progressive/payment/OrderConfirmLoader?"+"<?php echo $_SERVER['QUERY_STRING']; ?>";
    window.location.href=redirectUrl;
});
</script>
