<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<small class="copyright">
    <span><a href="https://www.forevercompanies.com/" target="_blank" title="Forever Companies" alt="Forever Companies">A Forever Company.</a> <?php echo date("Y"); ?> All Rights Reserved | <a href="https://www.diamondnexus.com/customer-service-privacy-policy.html" target="_blank" title="Privacy Policy" alt="Privacy Policy">Privacy Policy</a></span>
</small>