<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

$attributes = $block->getCssClass() ? ' class="' . $block->escapeHtmlAttr($block->getCssClass()) . ' order-summary'.'"' : '';
$attr = $block->getAttributes();

if (! empty($attr)){
    foreach ($block->getAttributes() as $attribute => $value){
        $attributes .= ' ' . $block->escapeHtml($attribute) . '="' . $block->escapeHtmlAttr($value) . '"';
    }
}
/* @noEscape */ echo '<'
    . $block->escapeHtml($block->getTag())
    . $attributes
    . '>'
    . $block->escapeHtml('Order Summary')
    . '</'
    . $block->escapeHtml($block->getTag())
    . '>';
