<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Checkout\Block\Registration */
?>

<script>
    require(['jquery'], function() {
        jQuery(document).ready(function() {
            jQuery("#create_account_form").submit(function() {

                var txtFormKey = jQuery("input[name='form_key']").val();
                var txtPassword = jQuery("input[name='password']").val();
                var url = "/fccheckout/createaccount/";

                jQuery.ajax({
                    url: url,
                    dataType: "json",
                    type: "POST",
                    data: {
                        form_key: txtFormKey,
                        password: txtPassword
                    },
                    cache: false,
                    success: function(response) {
                        if (response.success == true) {
                            alert("Account was created!");
                        } else {
                            alert(response.message);
                        }
                    }
                });
                return false;
            });
        });
    });
</script>

<form id="create_account_form" method="post" action="/fccheckout/createaccount/">
    <?php echo $block->getBlockHtml('formkey') ?>
    <h3 class="h3">Create an account to stay up to date on the status of your order.</h3>
    <div class="form-fields">
        <label>Password</label>
        <input type="text" name="password" />
        <button type="submit">Create Account</button>
    </div>
</form>