<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>

<div class="checkout-success">
    <?php if ($block->getOrderId()) : ?>
        <?php if ($block->getCanViewOrder()) : ?>
            <p><?= $block->escapeHtml(__('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeUrl($block->getViewOrderUrl()), $block->getOrderId())), ['a', 'strong']) ?></p>
        <?php else : ?>
            <p><?= $block->escapeHtml(__('Your order # is: <span>%1</span>.', $block->getOrderId()), ['span']) ?></p>
        <?php endif; ?>
    <?php endif; ?>

    <?= $block->getAdditionalInfoHtml() ?>

    <div class="success-content">
        <p>Here's what will happen next: Our jewelers will create your piece, if it features stones they will be carefully set, then they'll polish it to perfection and wrap it for mailing. We will email you a tracking number when your piece ships. Because we know how important this piece is, a signature by an adult is required for delivery! <a href="/learn/policies#shipping-delivery" title="Not Home" alt="Not Home">Not going to be home?</a>
    </div>

    <div class="success-page-features">
        <div class="calendar">
            <p class="calendar-title">Delivery Date</p>
            <?php /* From M1 Success Template Implementation
            <script>
                flatpickr.l10ns.default.weekdays.shorthand = ['S', 'M', 'T', 'W', 'T', 'F', 'S'];
                flatpickr('.js-calendar', {
                    inline: true,
                    defaultDate: '<?php echo ((strlen($block->getDeliveryDate()) > 0) ? $block->getDeliveryDate() : $ship_date); ?>'
                });
            </script>
            */ ?>
            <div class="delivery-date">
                <?php
                $deliveryDate = $block->getDeliveryDate();
                $deliveryDateWeekday = date("l", strtotime($deliveryDate));
                $deliveryDateMonth = date("F", strtotime($deliveryDate));
                $deliveryDateDay = date("d", strtotime($deliveryDate));
                ?>
                <h3 class="h3 weekday"><?php echo $deliveryDateWeekday; ?></h3>
                <p class="month"><?php echo $deliveryDateMonth; ?></p>
                <p class="day"><?php echo $deliveryDateDay; ?></p>
            </div>
            <div id="js-calendar-success" data-date="<?php echo $block->getDeliveryDate(); ?>"></div>
        </div>
        <div class="additional-success-blocks">
            <div class="email-block">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 16">
                    <path id="Union_54" data-name="Union 54" d="M0,16V0H24V16Zm1.75-1.75h20.5v-8.5L12.189,9.864,1.75,5.871ZM12.167,7.982,22.25,3.857V1.75H1.75V4Z" />
                </svg>
                <h3 class="h3">Watch your email for updates.<br>We'll be in touch every<br>step of the way!</h3>
            </div>
            <div class="featured-block">
                <h3 class="h3">Featured Collections</h3>
                <a href="#" title="Featured Collections" alt="Featured Collections">Shop Now</a>
            </div>
        </div>
    </div>
</div>