<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>

<div class="checkout-success">
    <?php if ($block->getOrderId()) : ?>
        <?php if ($block->getCanViewOrder()) : ?>
            <p><?= $block->escapeHtml(__('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeUrl($block->getViewOrderUrl()), $block->getOrderId())), ['a', 'strong']) ?></p>
        <?php else : ?>
            <p><?= $block->escapeHtml(__('Your order # is: <span>%1</span>.', $block->getOrderId()), ['span']) ?></p>
        <?php endif; ?>
    <?php endif; ?>

    <?= $block->getAdditionalInfoHtml() ?>

    <div class="success-content">
        <p>Here's what will happen next: Our jewelers will create your piece, if it features stones they will be carefully set, then they'll polish it to perfection and wrap it for mailing. We will email you a tracking number when your piece ships. Because we know how important this piece is, a signature by an adult is required for delivery! <a href="#" title="Not Home" alt="Not Home">Not going to be home?</a>
    </div>

    <div class="success-page-features">
        <div class="calendar">
            <p class="calendar-title">Estimated Ship Date</p>
            <?php /* From M1 Success Template Implementation
            <script>
                flatpickr.l10ns.default.weekdays.shorthand = ['S', 'M', 'T', 'W', 'T', 'F', 'S'];
                flatpickr('.js-calendar', {
                    inline: true,
                    defaultDate: '<?php echo ((strlen($block->getDeliveryDate()) > 0) ? $block->getDeliveryDate() : $ship_date); ?>'
                });
            </script>
            */ ?>
            <div class="delivery-date">
                <?php
                $deliveryDate = $block->getDeliveryDate();
                $deliveryDateWeekday = date("l", strtotime($deliveryDate));
                $deliveryDateMonth = date("F", strtotime($deliveryDate));
                $deliveryDateDay = date("d", strtotime($deliveryDate));
                ?>
                <h3 class="h3 weekday"><?php echo $deliveryDateWeekday; ?></h3>
                <p class="month"><?php echo $deliveryDateMonth; ?></p>
                <p class="day"><?php echo $deliveryDateDay; ?></p>
            </div>
            <div id="js-calendar-success" data-date="<?php echo $block->getDeliveryDate(); ?>"></div>
        </div>
        <div class="additional-success-blocks">
            <div class="email-block">
                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" focusable="false" style="-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);" preserveAspectRatio="xMidYMid meet" viewBox="0 0 1024 896">
                    <path d="M1023 168q1-3 1-6t-1-6l-2-6q-12-54-77-54H112q-30 0-57.5 11T13 137l-5 5q-10 11-7 26q-1 2-1 4v516q0 40 36 76t76 36h832q37 0 58.5-34t21.5-78V170.5l-1-2.5zm-911-8h832L512 505L81 161q8-1 31-1zm832 576H112q-9 0-20.5-8T72 708.5T64 688V230l427 341q9 8 21 8q12-1 21-8l427-341v462q0 44-16 44z" />
                    <rect x="0" y="0" width="1024" height="896" fill="rgba(0, 0, 0, 0)" /></svg>
                <h3 class="h3">Watch your email for updates. We'll be in touch every step of the way!</h3>
            </div>
            <div class="featured-block">
                <h3 class="h3">Featured Collections</h3>
                <a href="#" title="Featured Collections" alt="Featured Collections">Shop Now</a>
            </div>
        </div>
    </div>
</div>