version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - python --version
  pre_build:
    commands:
      - export STARTTIME=`date +%s`
      - export BUILDNAME="$GIT_BRANCH-`date +%Y-%m-%d`"
      - export BRANCH="$GIT_BRANCH"
      - export SOURCE_VERSION="$CODEBUILD_SOURCE_VERSION"
      - export FUNCTION_NAME="$LAMBDA_TO_UPDATE"
      - export username="$GITUSER"
      - export pass="$GITPASSWORD"
      - echo "BRANCH $BRANCH"
      - echo "SOURCE_VERSION $SOURCE_VERSION"
      - export task="$Taskid"
      - export accountId="$account"
      - export snstopic="$sns"
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - IMAGE_TAG=build-$(git rev-parse HEAD)
      - export efsid="$efs_standby"
      - export datasyncsg="$securitygroup"
      - export subnetid="$subnetId"
  build:
    commands:
      - echo Build started on `date`
      - echo Cloning remote GIT repo
      - git log --name-status HEAD^..HEAD
      - echo Building the Docker image...
      - docker build -t magento --cache-from magento:latest --build-arg REDIS_HOST=$redis --build-arg DB_HOST=$dbhost --build-arg DB_NAME=$dbname --build-arg DB_USER=$dbuser --build-arg DB_ROOT_PASSWORD=$dbrootpassword --build-arg VARNISH_HOST=$varnishhost --build-arg RABBIT_HOST=$rabbithost --build-arg RABBIT_PORT=$rabbitport --build-arg RABBIT_VHOST=$rabbitvhost --build-arg RABBIT_USER=$rabbituser --build-arg RABBIT_PASSWORD=$rabbitpassword --build-arg MAG_NAME=$magname --build-arg ELASTICSEARCH7_SERVER_HOSTNAME=$elasticsearchserverhostname --build-arg ELASTICSEARCH7_ENGINE=$catalogsearchengine --build-arg ELASTICSEARCH7_SERVER_PORT=$elasticsearchserverport --build-arg CRYPT=$CRYPT --build-arg MAG_ENV=$MAGENV --build-arg MAGENTO=$MAGENTO --build-arg NGINX_HOST=$NGINXHOST --build-arg VARNISH_BACKEND_HOST=$VARNISHBACKENDHOST --build-arg VARNISH_ACCESS_LIST=$VARNISHACCESSLIST --build-arg ADMIN_URL=$ADMINURL --build-arg BRAINTREE_ENV=$BRAINTREEENV --build-arg BRAINTREE_PUBLIC_KEY=$BRAINTREEPUBLICKEY --build-arg BRAINTREE_PRIVATE_KEY=$BRAINTREEPRIVATEKEY --build-arg BRAINTREE_SANDBOX_PUBLIC_KEY=$BRAINTREESANDBOXPUBLICKEY --build-arg BRAINTREE_SANDBOX_PRIVATE_KEY=$BRAINTREESANDBOXPRIVATEKEY --build-arg BRAINTREE_MERCHANT_ID=$BRAINTREEMERCHANTID --build-arg BRAINTREE_MERCHANT_ACCOUNT_ID=$BRAINTREEMERCHANTACCOUNTID --build-arg AFFIRM_GATEWAY_MODE=$AFFIRMGATEWAYMODE --build-arg AFFIRM_GATEWAY_PUBLIC_API_KEY_SANDBOX=$AFFIRMGATEWAYPUBLICAPIKEYSANDBOX --build-arg AFFIRM_GATEWAY_PRIVATE_API_KEY_SANDBOX=$AFFIRMGATEWAYPRIVATEAPIKEYSANDBOX --build-arg PROGRESSIVE_GATEWAY_MODE=$PROGRESSIVEGATEWAYMODE --build-arg PROGRESSIVE_GATEWAY_PUBLIC_API_KEY_DEMO=$PROGRESSIVEGATEWAYPUBLICAPIKEYDEMO --build-arg PROGRESSIVE_GATEWAY_PRIVATE_API_KEY_DEMO=$PROGRESSIVEGATEWAYPRIVATEAPIKEYDEMO --build-arg PROGRESSIVE_GATEWAY_MERCHANT_ID=$PROGRESSIVEGATEWAYMERCHANTID --build-arg PROGRESSIVE_GATEWAY_STORE_ID=$PROGRESSIVEGATEWAYSTOREID --build-arg PROGRESSIVE_GATEWAY_DEMO_API_URL=$PROGRESSIVEGATEWAYDEMOAPIURL --build-arg SHIP_LOG=$SHIPLOG --build-arg SMTP_PRODUCT_KEY=$SMTPPRODUCTKEY --build-arg SMTP_PASSWORD=$SMTPPASSWORD --build-arg BASE_SMTP_PASSWORD=$BASESMTPPASSWORD --build-arg WWW_FA_SMTP_PASSWORD=$WWWFASMTPPASSWORD --build-arg WWW_1215_SMTP_PASSWORD=$WWW1215SMTPPASSWORD --build-arg WORDPRESS=$WORDPRESS --build-arg SF_HOST=$SFHOST --build-arg SF_CLIENT_ID=$SFCLIENTID --build-arg SF_CLIENT_SECRET=$SFCLIENTSECRET --build-arg SF_EMAIL=$SFEMAIL --build-arg SF_PASSWD=$SFPASSWD --build-arg DN_BASE_URL=$DNBASEURL --build-arg FA_BASE_URL=$FABASEURL --build-arg TF_BASE_URL=$TFBASEURL --build-arg BUILD=prod .
      - docker tag magento:latest $REPOURL/magento:latest
      - docker tag magento:latest $REPOURL/magento:$IMAGE_TAG
      - docker images 
      - docker create magento
      - CONTAINER=$(docker ps -a | grep magento | awk '{print $1}')
      - docker ps -a 
      - echo $CONTAINER
      - docker cp -a $CONTAINER:/var/www/magento/. .
      - chown 1000:1000 -R .
      - bash prodsync.sh $task $accountId $efsid $datasyncsg $subnetid
      - sleep 3
      - echo Pushing the Docker images...
      - docker push $REPOURL/magento:latest
      - docker push $REPOURL/magento:$IMAGE_TAG
      - aws sns publish --topic-arn $snstopic --message "datasync perfomed"
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
