version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - python --version
  pre_build:
    commands:
      - export STARTTIME=`date +%s`
      - export BUILDNAME="$GIT_BRANCH-`date +%Y-%m-%d`"
      - export BRANCH="$GIT_BRANCH"
      - export SOURCE_VERSION="$CODEBUILD_SOURCE_VERSION"
      - export FUNCTION_NAME="$LAMBDA_TO_UPDATE"
      - export username="$GITUSER"
      - export pass="$GITPASSWORD"
      - echo "BRANCH $BRANCH"
      - echo "SOURCE_VERSION $SOURCE_VERSION"
  build:
    commands:
      - echo Build started on `date`
      - echo Cloning remote GIT repo
      - echo clone
      - pwd
      - ls
      - pip install dirsync
      - cp -p -r --backup=numbered `find ~/ -name dirsync -a -type d` ./
      - ls 
      - zip -qr source.zip ./ -x '.git/*'
      - aws s3 cp source.zip s3://mag2-prod-codebuild/source.zip
      - aws lambda update-function-code --function-name $FUNCTION_NAME --s3-bucket mag2-prod-codebuild --s3-key source.zip
      - sleep 3
      #- aws sns publish {} topic
  post_build:
    commands:
      - echo Build completed on `date`
      - pwd
      - ls -al
artifacts:
  files:
    - '**/*'
