version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - python --version
  pre_build:
    commands:
      - export STARTTIME=`date +%s`
      - export BUILDNAME="$GIT_BRANCH-`date +%Y-%m-%d`"
      - export BRANCH="$GIT_BRANCH"
      - export SOURCE_VERSION="$CODEBUILD_SOURCE_VERSION"
      - export FUNCTION_NAME="$LAMBDA_TO_UPDATE"
      - export username="$GITUSER"
      - export pass="$GITPASSWORD"
      - echo "BRANCH $BRANCH"
      - echo "SOURCE_VERSION $SOURCE_VERSION"
      - export task="$Taskid"
      - export accountId="$account"
  build:
    commands:
      - echo Build started on `date`
      - echo Cloning remote GIT repo
      - pwd
      - ls
      - aws s3 sync . s3://mag2-dev-codebuild/magento --exclude ".git/*"  --delete
      - bash datasync.sh $task $accountId
      - sleep 3
  post_build:
    commands:
      - echo Build completed on `date`
      - pwd
      - ls -al
artifacts:
  files:
    - '**/*'
