<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * @var \Magento\Review\Block\Customer\Recent $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php if ($block->getReviews() && count($block->getReviews())) : ?>
    <div class="block block-reviews-dashboard">
        <div class="block-title">
            <strong><?= $block->escapeHtml(__('My Recent Reviews')) ?></strong>
            <a class="action view" href="<?= $block->escapeUrl($block->getAllReviewsUrl()) ?>">
                <span><?= $block->escapeHtml(__('View All')) ?></span>
            </a>
        </div>
        <div class="block-content">
            <ol class="items">
                <?php foreach ($block->getReviews() as $_review) : ?>
                    <li class="item">
                        <strong class="product-name">
                            <a href="<?= $block->escapeUrl($block->getReviewUrl($_review->getReviewId())) ?>">
                                <?= $block->escapeHtml($_review->getName()) ?>
                            </a>
                        </strong>
                        <?php if ($_review->getSum()) : ?>
                            <?php $rating = $_review->getSum() / $_review->getCount() ?>
                            <div class="rating-summary">
                                <span class="label"><span><?= $block->escapeHtml(__('Rating')) ?>:</span></span>
                                <div class="rating-result" title="<?= $block->escapeHtmlAttr($rating) ?>%">
                                    <span>
                                        <span><?= $block->escapeHtml($rating) ?>%</span>
                                    </span>
                                </div>
                                <?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                    "width:" . $block->escapeHtmlAttr($rating) . "%",
                                    'div.rating-result>span:first-child'
                                ) ?>
                            </div>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
            </ol>
        </div>
    </div>
<?php endif; ?>

<div class="account-additional-note">
    <strong class="box-title"><span>Shipping Carrier Tips</span></strong>
    <p>Follow these tips to ensure the safe delivery of your package.</p>
    <ul>
        <li>An adult over the age of 18 is required to sign for your package.</li>
        <li>You must request a change of address at least 24 hours before your order ships. Once the item has left our facility, we are not able to change the address.</li>
        <li>Packages sent USPS will arrive at your usual drop off time.</li>
        <li>In the event of a missed delivery, your package will be taken to a local holding facility for pick up at your convenience. Contact your shipping carrier for more information.</li>
    </ul>
</div>