<?php
/**
 * Delivery date template
 *
 * Template is used to include a delivery date in order/shipment emails. The template pulls the order from the related
 * order/shipments and then uses the shipperHQ carrier group helper to pull the delivery date. The template doesn't
 * print a delivery date if none is found.
 *
 * To include in email use the following:
 * {{block class="Magento\Framework\View\Element\Template" template="ForeverCompanies_ShipmentTracking::delivery_date.phtml" order_id=$order.entity_id}}
 *
 */

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$carrierGroupHelper = $objectManager->create('ShipperHQ\Shipper\Helper\CarrierGroup');

$shippingDetail = $carrierGroupHelper->getOrderCarrierGroupInfo($block->getOrderId());
?>

<?php if (isset($shippingDetail['delivery_date']) === true): ?>
    <?=date("D, M j", strtotime($shippingDetail['delivery_date']))?>
<?php endif; ?>