<?php
// Include site specific file via domain check
$tealInclude = '';
$hostAry = explode(".",$_SERVER['HTTP_HOST']);
switch ($hostAry[1]) {
    case 'diamondnexus': $tealInclude = 'tealium-dn.js';
        break;
    case 'foreverartisans': $tealInclude = 'tealium-fa.js';
        break;
    case '1215diamonds': $tealInclude = 'tealium-tf.js';
        break;
}
if (!empty($tealInclude)): ?>
    <script src="<?php echo $block->getViewFileUrl('ForeverCompanies_Tealium::js/' . $tealInclude) ?>"></script>
    <script src="<?php echo $block->getViewFileUrl('ForeverCompanies_Tealium::js/tealium-global.js') ?>"></script>
<?php endif; ?>