<?php

/**
 * Astound
 * NOTICE OF LICENSE
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to codemaster@astoundcommerce.com so we can send you a copy immediately.
 *
 * @category  Affirm
 * @package   Astound_Affirm
 * @copyright Copyright (c) 2016 Astound, Inc. (http://www.astoundcommerce.com)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Copyright (c) 2016 Astound, Inc. (http://www.astoundcommerce.com).
 * Modified by Prog Leasing, LLC. Copyright (c) 2018, Prog Leasing, LLC.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Payment\Block\Info $block
 * @see \Magento\Payment\Block\Info
 */
$specificInfo = $block->getSpecificInformation();
$title = $block->escapeHtml($block->getMethod()->getTitle());
?>
<dl class="payment-method">
    <div class="admin__page-section-item-content">
        <table class="admin__table-secondary order-account-information-table>
            <caption class="table-caption"><?php /* @noEscape */ echo $title; ?></caption>
            <?php if ($specificInfo):?>
                <?php foreach ($specificInfo as $label => $value):?>
                    <tr>
                        <th scope="row"><?php echo $block->escapeHtml($label)?></th>
                        <td>
                            <?php /* @noEscape */ echo nl2br($block->escapeHtml(trim(implode("\n", $block->getValueAsArray($value, true)))));?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php endif;?>
        </table>
    </div>
</dl>
<?php echo $block->getChildHtml()?>
