<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\CustomerData $block */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/customer-data": {
                "sectionLoadUrl": "<?= $block->escapeJs($block->getCustomerDataUrl('customer/section/load')) ?>",
                "expirableSectionLifetime": <?= (int)$block->getExpirableSectionLifetime() ?>,
                "expirableSectionNames": <?= /* @noEscape */ $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($block->getExpirableSectionNames()) ?>,
                "cookieLifeTime": "<?= $block->escapeJs($block->getCookieLifeTime()) ?>",
                "updateSessionUrl": "<?= $block->escapeJs($block->getCustomerDataUrl('customer/account/updateSession')) ?>"
            }
        }
    }
</script>

<div class="account-additional-note">
    <strong class="box-title"><span>Shipping Carrier Tips</span></strong>
    <p>Follow these tips to ensure the safe delivery of your package.</p>
    <ul>
        <li>An adult over the age of 18 is required to sign for your package.</li>
        <li>You must request a change of address at least 24 hours before your order ships. Once the item has left our facility, we are not able to change the address.</li>
        <li>Packages sent USPS will arrive at your usual drop off time.</li>
        <li>In the event of a missed delivery, your package will be taken to a local holding facility for pick up at your convenience. Contact your shipping carrier for more information.</li>
    </ul>
</div>