<?php
    /** @var $block \Magento\Sales\Block\Order\Email\Items */

    $_order = $block->getOrder();

    $_product = null;
    $_orderHasBand = false;
    $_metalType = "14k White Gold";
?>
<?php if ($_order): ?>

    <?php
        $itemList = $_order->getAllItems();

        // look for a matching band or wedding band
        foreach($itemList as $item)
        {
            if( $item->getAttributeSetId() == 27 || substr($item->getSku(), 0, 4) == "LRWB" )
            {
                // do not include cross-sells if they purchased a band
                $_orderHasBand = true;
                break;
            }
        }

        foreach($itemList as $item)
        {
            if( substr($item->getSku(), 0, 4) == "LREN" ) {
                $_product = $item;
                break;
            }

        }
        ?>
    
    <?php if ($_product && $_product->getId() > 0 && $_orderHasBand == false ): ?>
        <?php $crossProducts = $this->getCrossSellProducts($_product->getProduct()); ?>
        <table widht="100%">
            <tr>
            <?php if (count($crossProducts) > 0): ?>
                <?php foreach($crossProducts as $crossProduct): ?>
                    <td>
                        <span><?=$crossProduct['name']?></span>
                        <br />
                        <a href="<?=$crossProduct['url']?>"><img width="200" src="<?=$crossProduct['image']?>" alt="<?=$crossProduct['name']?>" /></a>
                    </td>
                <?php endforeach; ?>
            <?php endif; ?>
            </tr>
        </table>
    <?php endif; ?>
<?php endif; ?>