<?php

use DiamondNexus\Multipay\Block\Order\History;
use Magento\Framework\Data\Helper\PostHelper;
use Magento\Framework\Exception\LocalizedException;
use Magento\Sales\Block\Order\History\Container;
use Magento\Sales\Helper\Reorder;

/** @var History $block */
/** @var Escaper $escaper */

?>
<?php $_orders = $block->getOrders(); ?>
<?= $block->getChildHtml('info') ?>
<?php if ($_orders && count($_orders)) : ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= $escaper->escapeHtml(__('Orders')) ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col id"><?= $escaper->escapeHtml(__('Order #')) ?></th>
                <th scope="col" class="col date"><?= $escaper->escapeHtml(__('Date')) ?></th>
                <?= $block->getChildHtml('extra.column.header') ?>
                <th scope="col" class="col shipping"><?= $escaper->escapeHtml(__('Ship To')) ?></th>
                <th scope="col" class="col total"><?= $escaper->escapeHtml(__('Order Total')) ?></th>
                <th scope="col" class="col status"><?= $escaper->escapeHtml(__('Status')) ?></th>
                <th scope="col" class="col actions"><?= $escaper->escapeHtml(__('Action')) ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($_orders as $_order) : ?>
                <?php $name = $_order->getShippingAddress()->getName(); ?>
                <tr>
                    <td data-th="<?= $escaper->escapeHtmlAttr(__('Order #')) ?>"
                        class="col id"><?= $escaper->escapeHtml($_order->getRealOrderId()) ?></td>
                    <td data-th="<?= $escaper->escapeHtmlAttr(__('Date')) ?>" class="col date"><?= /* @noEscape */
                        $block->formatDate($_order->getCreatedAt()) ?></td>
                    <?php /** @var Container $extra */$extra = $block->getChildBlock('extra.container'); ?>
                    <?php try { if ($extra) : ?>
                            <?php $extra->setOrder($_order); ?>
                            <?= $extra->getChildHtml() ?>
                    <?php endif;
                    } catch (LocalizedException $e) { echo '';
                    } ?>
                    <td data-th="<?= $escaper->escapeHtmlAttr(__('Ship To')) ?>"
                        class="col shipping"><?=
                        $_order->getShippingAddress() ? $escaper->escapeHtml($name) : '&nbsp;' ?></td>
                    <td data-th="<?= $escaper->escapeHtmlAttr(__('Order Total')) ?>"
                        class="col total"><?= /* @noEscape */
                        $_order->formatPrice($_order->getGrandTotal()) ?></td>
                    <td data-th="<?= $escaper->escapeHtmlAttr(__('Status')) ?>"
                        class="col status"><?= $escaper->escapeHtml($_order->getStatusLabel()) ?></td>
                    <td data-th="<?= $escaper->escapeHtmlAttr(__('Actions')) ?>" class="col actions">
                        <a href="<?= $escaper->escapeUrl($block->getViewUrl($_order)) ?>" class="action view">
                            <span><?= $escaper->escapeHtml(__('View Order')) ?></span>
                        </a>
                        <?php if ($block->canPayNow($_order)) : ?>
                            <a  onclick="var newwin = window.open(
                                            '<?= $escaper->escapeUrl($block->getPayNowUrl($_order->getId())) ?>',
                                            'newwin',
                                            'resizable=0,menubar=0,height=600,width=475'
                                        );
                                        newWin.opener = null;
                                        newWin.focus();"
                                href="javascript:void(0)"
                                class="action order">
                                <span><?= $escaper->escapeHtml(__('Pay now')) ?></span>
                            </a>
                        <?php endif ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()) : ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else : ?>
    <div class="message info empty"><span><?= $escaper->escapeHtml(__('You have placed no orders.')) ?></span></div>
<?php endif ?>
