<?php
use DiamondNexus\Multipay\Block\Order\Paynow;
use Magento\Framework\Escaper;

/** @var Paynow $block */
/** @var Escaper $escaper */

$code = 'multipay';
$orderId = (int) $block->getData('order_id');

# load the increment id
$incrementId = $block->getIncrementId();
# get the amount due
$amountDue = $block->getTotalDue();

$paypalClientId = $escaper->escapeHtml($block->getClientId());
$openForm = $escaper->escapeHtml($block->getOpenForm());
$btn = $escaper->escapeHtml('.paypal-button-widget');
$errorAlert = "There was an error processing your payment. Please call customer service.";
$src = $escaper->escapeHtml('https://www.paypal.com/sdk/js?client-id=' . $paypalClientId);
$jsCheckoutGuest = "$('#paypal-in-context-checkout-guest " . $btn;
$jsCheckout = "$('#paypal-in-context-checkout " . $btn;

$currentYear = date("Y");
$maxYear = $currentYear + 12;
?>

<script
    src="<?= /** @noEscape */
    $src ?>&currency=USD&disable-funding=credit,card&integration-date=2021-05-05"
    data-order-id="<?= $escaper->escapeHtml($incrementId); ?>"></script>

<style type="text/css">

.nav-toggle {display:none;}

.paynow-container .content-container {
    width:100%;
    border-bottom: solid gray 1px;
    margin-top: 10px;
    margin-bottom: 10px;
}
.paynow-container h3 { margin-top: 0; }
.paynow-container fieldset { border: none; }
.paynow-container .cc-form { display:none; }
.paynow-container .payment-method-options>div {margin-top: 10px;}
.paynow-container .submit-payment-button {margin-top: 20px;}

 /*
 * Style for buttons
 */
.btn {
    display: inline-block;
    width:100%;
    height: 50px;
    font-size: 16px;
    font-weight: normal;
    font-family: Arial, Helvetica, sans-serif;
    padding: 2px 12px;
    margin-bottom: 0;
    line-height: 20px;
    text-align: center;
    vertical-align: middle;
    cursor: pointer;
    color: #ffffff;
    text-decoration: none;
    background-color: #000000;
    border: 0;
    -webkit-border-radius: 5px;
    -moz-border-radius: 5px;
    border-radius: 5px;
    *margin-left: .3em;
    -webkit-box-shadow: inset 0 1px 0 rgba(255,255,255,.2), 0 1px 2px rgba(0,0,0,.05);
    -moz-box-shadow: inset 0 1px 0 rgba(255,255,255,.2), 0 1px 2px rgba(0,0,0,.05);
    box-shadow: inset 0 1px 0 rgba(255,255,255,.2), 0 1px 2px rgba(0,0,0,.05);
}
.btn:hover,
.btn:focus,
.btn:active,
.btn.active,
.btn.disabled,
.btn[disabled] {
    color: #ffffff;
    background-color: #010101;
}
.btn:active,
.btn.active {
    background-color: #010101;
}
.btn:first-child {
    *margin-left: 0;
}
.btn:hover,
.btn:focus {
    color: #ffffff;
    text-decoration: none;
}
</style>

<div id="popup-modal-add-payment" class="paynow-container">
    <div class="content-container">
        <h3>Payment for order #<?=$escaper->escapeHtml($incrementId)?></h3>
        <div>Amount Due:</div>
        <div><?=$escaper->escapeHtml($amountDue)?></div>
    </div>
    <div class="payment-buttons-container">
        <div id="paypal-button-container"></div>
        <!--
            **** Removed for PCI Compliance ****
            <button class="debit-credit-button btn">
                <span>Debit or Credit Card</span>
            </button>
        -->
    </div>
    
    <script>
        require([
            'jquery'
        ], function ($) {
            
            <?php if ($openForm): ?>
                jQuery(".payment-buttons-container").hide();
                jQuery(".cc-form").fadeIn();
            <?php endif; ?>
            
            /*
                jQuery(".debit-credit-button").on( "click", function() {
                    jQuery(".payment-buttons-container").hide();
                    jQuery(".cc-form").fadeIn();
                });
            */
            
            function sendPayment(details) {
                
                //jQuery.fancybox.showLoading();

                jQuery.ajax({
                    method: "<?=$escaper->escapeHtml('POST') ?>",
                    dataType: "JSON",
                    url: "<?= $escaper->escapeUrl($block->getPaypalActionUrl()); ?>",
                    data: {
                        order_id: <?= /** @noEscape */ $orderId; ?>,
                        details: details
                    }
                }).done(function (response) {
                    if (response.success == true) {
                        location.href = "<?=$escaper->escapeUrl($block->getPaypalPaymentCompleteUrl($orderId))?>";
                    } else {
                        alert('<?=$escaper->escapeHtml($errorAlert)?>');
                        //jQuery.fancybox.hideLoading();
                    }
                });
            }

            paypal.Buttons({
                createOrder: function (data, actions) {
                    return actions.order.create({
                        purchase_units: [{
                            amount: {
                                value: <?=$escaper->escapeHtml($amountDue); ?>
                            },
                            invoice_id: "<?=$escaper->escapeHtml($incrementId); ?>"
                        }],
                        application_context: {
                            shipping_preference: 'NO_SHIPPING'
                        }
                    });
                },
                onApprove: function (data, actions) {
                    // This function captures the funds from the transaction.
                    return actions.order.capture().then(function (details) {
                        if (details.intent == "CAPTURE"
                            && details.status == "COMPLETED"
                            && details.purchase_units[0].amount.value == <?=$escaper->escapeHtml($amountDue)?>) {
                            sendPayment(details);
                        } else {
                            alert('<?=$escaper->escapeHtml($errorAlert) ?>');
                        }
                    });
                },
                onCancel: function () {
                    //jQuery.fancybox.hideLoading();
                },
                onError: function (err) {
                    if(err != null) {
                        alert(
                            "Sorry there was an error processing your transaction.\n" +
                            "Please call 1-800-509-4990 if you continue to experience issues.\n" +
                            err
                        );
                    }
                }
            }).render('#paypal-button-container');
        })
    </script>

    <div class="cc-form">
        <?php /* REMOVED FOR PCI COMPLIANCE */ ?>
    </div>
</div>
