<?php
use DiamondNexus\Multipay\Block\Order\Paynow;

/** @var Paynow $block */

$code = 'multipay';
?>

<div id="popup-modal-add-payment">

    <form action="<?= $block->escapeUrl($block->getFormUrl()) ?>" method="post"
          id="order-view-add-warranty-add-payment-form"
          data-mage-init='{"validation":{"rules": {"multipay_payment_method": {"required":true}}}}'>
        <fieldset class="admin__fieldset payment-method" id="payment_form_multipay">

            <!-- choose the payment method -->
            <fieldset class="admin__fieldset payment-method-options multipay-fieldset"
                      id="payment_form_multipay_method">

                <div class="admin__field-option _required">
                    <input id="multipay_method_cc" class="admin__control-radio" value="1" type="radio"
                           name="multipay_payment_method" data-validate='{"required":true}'/>
                    <label class="label" for="multipay_method_cc">
                        <span><?= $block->escapeHtml(__('Credit Card')) ?></span>
                    </label>
                </div>
                <div class="admin__field-option _required">
                    <input id="multipay_method_paypal_offline" class="admin__control-radio" value="6" type="radio"
                           name="multipay_payment_method" data-validate='{"required":true}'
                           onclick="location.href = ""
                    />
                    <label class="label" for="multipay_method_paypal_offline">
                        <span><?= $block->escapeHtml(__('Paypal')) ?></span>
                    </label>
                </div>
            </fieldset>

            <!-- choose full payment or partial payment -->
            <fieldset class="admin__fieldset payment-method-options multipay-fieldset"
                      id="payment_form_multipay_amount">
                <div class="admin__field-option _required">
                    <input id="multipay_method_total_balance" class="admin__control-radio" value="1" type="radio"
                           name="multipay_option_total" data-validate='{"required":true}'/>
                    <label class="label" for="multipay_method_total_balance">
                        <span><?= $block->escapeHtml(__('Total Amount')) ?></span>
                    </label>
                </div>
                <div class="admin__field-option _required">
                    <input id="multipay_method_partial_balance" class="admin__control-radio" value="2" type="radio"
                           name="multipay_option_total" data-validate='{"required":true}'/>
                    <label class="label" for="multipay_method_partial_balance">
                        <span><?= $block->escapeHtml(__('Partial Amount')) ?></span>
                    </label>
                </div>
            </fieldset>

            <!-- amount due -->
            <div class="payment-method-options multipay-fieldset" id="payment_form_multipay_amount_due">
                <div class="admin__field field-vat-number">
                    <label class="label admin__field-label" for="multipay_amount_due">
                        <span><?= $block->escapeHtml(__('Amount Due')) ?></span>
                    </label>
                </div>
                <div class="admin__field-control control">
                    <input id="multipay_amount_due" readonly="readonly"
                           class="input-text admin__control-text disabled"
                           value="<?= $block->escapeHtml($block->getBalanceAmount()) ?>" type="number" step="0.01"
                           name="multipay_amount_due"/>
                </div>
            </div>

            <!-- partial payment form -->
            <div class="payment-method-options multipay-fieldset">
                <div class="admin__field">
                    <label class="label admin__field-label" for="multipay_option_partial">
                        <span><?= $block->escapeHtml(__('Amount To Pay')) ?></span>
                    </label>
                </div>
                <div class="admin__field-control control">
                    <input id="multipay_option_partial" class="input-text admin__control-text" value=""
                           type="number"
                           step="0.01"
                           name="multipay_option_partial"/>
                </div>

                <div class="admin__field multipay-add-margin-top">
                    <label class="label admin__field-label" for="multipay_new_balance">
                        <span><?= $block->escapeHtml(__('Balance Due')) ?></span>
                    </label>
                </div>
                <div class="admin__field-control control">
                    <input readonly="readonly" id="multipay_new_balance"
                           class="input-text admin__control-text disabled"
                           value="<?= $block->escapeHtml($block->getBalanceAmount()) ?>" type="number" step="0.01"
                           name="multipay_new_balance"/>
                </div>
            </div>

            <!-- credit card info form -->
            <div class="payment-method-options multipay-fieldset">
                <div class="admin__field-control">
                    <label class="label admin__field-label">
                        <span><?= $block->escapeHtml(__('Credit Card Number')) ?></span>
                    </label>
                    <div class="admin__field-control control">
                        <input id="<?= $block->escapeHtmlAttr($code) ?>_cc_number"
                               name="multipay_cc_number"
                               class="admin__control-text hosted-control"/>
                    </div>
                </div>

                <div class="admin__field-control">
                    <label class="label admin__field-label">
                        <span><?= $block->escapeHtml(__('Expiration Date')) ?></span>
                    </label>
                    <div class="admin__field-control control">
                        <div class="hosted-date-wrap">
                            <input id="<?= $block->escapeHtmlAttr($code) ?>_cc_exp_month"
                                   name="multipay_cc_exp_month"
                                   class="admin__control-text hosted-control hosted-date"/>

                            <input id="<?= $block->escapeHtmlAttr($code) ?>_cc_exp_year"
                                   name="multipay_cc_exp_year"
                                   class="admin__control-text hosted-control hosted-date"/>
                        </div>
                    </div>
                </div>
                <div class="admin__field-control control">
                    <label class="label admin__field-label">
                        <span><?= $block->escapeHtml(__('CVV')) ?></span>
                    </label>
                    <input id="<?= $block->escapeHtmlAttr($code) ?>_cvv_number"
                           name="multipay_cvv_number"
                           class="admin__control-text hosted-control"/>
                </div>
            </div>

            <input type="hidden" id="<?= $block->escapeHtmlAttr($code) ?>_payment_method_nonce"
                   name="payment_method_nonce"/>
            <input type="submit" name="Submit" style="display:none;">
        </fieldset>

        <input type="submit" value="Submit" id="order-view-add-warranty-add-payment">
        <input type="hidden" name="order_id" value="<?= $block->getData('order_id') ?>">
    </form>
</div>
