<?php

use DiamondNexus\Multipay\Block\Order\Paypal;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */

/** @var Paypal $block */
# get the order id from the url
$id = $block->getData('order_id');
# load the increment id
$incrementId = $block->getIncrementId();
# get the amount due
$amount = $escaper->escapeHtml($block->getBalanceAmount());
$paypalClientId = $block->getClientId();
$btn = $escaper->escapeHtml('.paypal-button-widget');
$errorAlert = "There was an error processing your payment. Please call customer service.";
$src = $escaper->escapeHtml('https://www.paypal.com/sdk/js?client-id=' . $paypalClientId);
$jsCheckoutGuest = "$('#paypal-in-context-checkout-guest " . $btn;
$jsCheckout = "$('#paypal-in-context-checkout " . $btn;
?>

<style type="text/css">
    .payment dl {
        width: 460px;
    }

    .payment dl dt {
        width: 150px;
        padding: 2px;
        float: left;
        clear: both;
    }

    .payment dl dd {
        width: 100%;
        padding: 2px;
        float: right;
        margin-left: 0;
    }

    ul.errors {
        color: #cc0000;
        list-style-type: disc;
        margin: 0 0 0 15px;
        padding: 0 0 15px 0;
    }

    /*
    * Style for buttons
    */
    .btn {
        display: inline-block;
        *display: inline;
        /* IE7 inline-block hack */
        font-family: Arial, Helvetica, sans-serif;
        *zoom: 1;
        padding: 2px 12px;
        margin-bottom: 0;
        font-size: 11px;
        font-weight: bold;
        line-height: 20px;
        text-align: center;
        vertical-align: middle;
        cursor: pointer;
        color: #fff;
        text-shadow: 0 1px 1px rgba(219, 83, 33, 0.75);
        text-decoration: none;
        background-color: #f86e3d;
        background-image: -moz-linear-gradient(top, #f86e3d, #db5321);
        background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#f86e3d), to(#db5321));
        background-image: -webkit-linear-gradient(top, #f86e3d, #db5321);
        background-image: -o-linear-gradient(top, #f86e3d, #db5321);
        background-image: linear-gradient(to bottom, #f86e3d, #db5321);
        background-repeat: repeat-x;
        filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#f86e3d', endColorstr='#db5321');
        border-color: #db5321 #db5321 #db5321;
        border-color: rgba(219, 83, 33, 0.1) rgba(219, 83, 33, 0.1) rgba(219, 83, 33, 0.25);
        *background-color: #db5321;
        /* Darken IE7 buttons by default so they stand out more given they won't have borders */

        filter: progid:DXImageTransform.Microsoft.gradient(enabled=false);
        border: 1px solid #db5321;
        *border: 0;
        -webkit-border-radius: 2px;
        -moz-border-radius: 2px;
        border-radius: 2px;
        *margin-left: .3em;
        -webkit-box-shadow: inset 0 1px 0 rgba(255, 255, 255, .2), 0 1px 2px rgba(0, 0, 0, .05);
        -moz-box-shadow: inset 0 1px 0 rgba(255, 255, 255, .2), 0 1px 2px rgba(0, 0, 0, .05);
        box-shadow: inset 0 1px 0 rgba(255, 255, 255, .2), 0 1px 2px rgba(0, 0, 0, .05);
    }

    .btn:hover,
    .btn:focus,
    .btn:active,
    .btn.active,
    .btn.disabled,
    .btn[disabled] {
        color: #ffffff;
        background-color: #db5321;
        *background-color: #db5321;
    }

    .btn:active,
    .btn.active {
        background-color: #f86e3d \9;
    }

    .btn:first-child {
        *margin-left: 0;
    }

    .btn:hover,
    .btn:focus {
        color: #ffffff;
        text-decoration: none;
        background-position: 0 -15px;
        -webkit-transition: background-position 0.1s linear;
        -moz-transition: background-position 0.1s linear;
        -o-transition: background-position 0.1s linear;
        transition: background-position 0.1s linear;
    }

    .paypal-button-container .paypal-button-number-0 {
        border: solid black 1px;
        float: right;
    }

    .paypal-button-container .paypal-button-number-1 {
        float: left;
    }

</style>
<script
    src="<?= /** @noEscape */
    $src ?>&currency=USD&disable-funding=credit&integration-date=2020-10-01"
    data-order-id="<?= $escaper->escapeHtml($incrementId); ?>"></script>
<form action="<?= $escaper->escapeUrl($block->getPaypalUrl()) ?>" method="post">
    <input type="hidden" name="order_id" value="<?= $block->escapeHtml($id); ?>"/>
    <div class="my-account">
        <div class="dashboard">
            <div id="logo">
                <img src="<?= $escaper->escapeHtml($block->getPaypalLogo()) ?>" width="240"
                     border="0" alt=""/>
            </div>
            <div class="page-title">
                <h1>Payment for order #<?= $escaper->escapeHtml($incrementId); ?></h1>
            </div>
            <?php if ($block->getErrors()) : ?>
                <ul class="errors">
                    <?php foreach ($block->getErrors() as $error) : ?>
                        <li><?= $block->escapeHtml($error) ?></li>
                    <?php endforeach ?>
                </ul>
            <?php endif ?>
            <div class="paymentsContainer">
                <!-- this is the actual field that passes our payment amount -->
                <div class="payments">
                    <div class="payment" id="paymentStandard">
                        <dl>
                            <dt><label>Amount Due:</label></dt>
                            <dd><?= $escaper->escapeHtml(number_format($amount, 2)); ?></dd>
                        </dl>
                        <div style="clear:both;"></div>
                        <dl style="border-top: 1px solid #ccc; padding-top: 15px;">
                            <dt>&nbsp;</dt>
                            <dd>
                                <div id="paypal-button-container"></div>

                                <script>
                                    require([
                                        'jquery'
                                    ], function ($) {
                                        $(".paypal-guest-option").on("click", function () {
                                            <?= /** @noEscape */ $jsCheckoutGuest ?>
                                            ').trigger('
                                            click
                                            ');
                                            return;
                                        });
                                        $(".paypal-standard-option").on("click", function () {
                                            <?= /** @noEscape */ $jsCheckout ?>
                                            ').trigger('
                                            click
                                            ');
                                            return;
                                        });

                                        function sendPayment(details) {

                                            $.fancybox.showLoading();

                                            $.ajax({
                                                method: "<?= $escaper->escapeHtml('POST') ?>",
                                                dataType: "JSON",
                                                url: "<?= $escaper->escapeUrl($block->getPaypalActionUrl()); ?>",
                                                data: {
                                                    order_id: <?= /** @noEscape */ $id; ?>,
                                                    details: details
                                                }
                                            }).done(function (response) {
                                                if (response.success == true) {
                                                    location.href = "<?= /** @noEscape */ $block->getPaypalUrl($id) ?>";
                                                } else {
                                                    alert('<?=/** @noEscape */ $errorAlert ?>');
                                                    $.fancybox.hideLoading();
                                                }
                                            });

                                        }

                                        paypal.Buttons({
                                            createOrder: function (data, actions) {
                                                return actions.order.create({
                                                    purchase_units: [{
                                                        amount: {
                                                            value: <?= /** @noEscape */ $amount; ?>
                                                        },
                                                        invoice_id: "<?= /** @noEscape */ $incrementId; ?>"
                                                    }],
                                                    application_context: {
                                                        shipping_preference: 'NO_SHIPPING'
                                                    }
                                                });
                                            },
                                            onApprove: function (data, actions) {
                                                // This function captures the funds from the transaction.
                                                return actions.order.capture().then(function (details) {
                                                    if (details.intent == "CAPTURE"
                                                        && details.status == "COMPLETED"
                                                        && details.purchase_units[0].amount.value == <?= $amount; ?>) {
                                                        sendPayment(details);
                                                    } else {
                                                        alert('<?=$escaper->escapeHtml($errorAlert) ?>');
                                                    }
                                                });
                                            },
                                            onCancel: function () {
                                                $.fancybox.hideLoading();
                                            }
                                        }).render('#paypal-button-container');
                                    })
                                </script>
                            </dd>
                        </dl>
                        <div style="clear:both;"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
