<?php

use ForeverCompanies\CustomAttributes\Block\Adminhtml\Product\Helper\Form\Gallery\Content;

/** TODO: Add 3 new fields for media */

/** @var $block Content */
$elementName = $block->getElement()->getName() . '[images]';
$formName = $block->getFormName();
$cloudinaryMLwidgetOprions = $block->getCloudinaryMediaLibraryWidgetOptions();
?>

<div class="row">
    <div class="add-video-button-container">
        <button id="add_video_button"
            title="<?= $block->escapeHtml(__('Add Video')) ?>"
            data-role="add-video-button"
            type="button"
            class="action-secondary"
            data-ui-id="widget-button-1">
            <span><?= $block->escapeHtml(__('Add Video')) ?></span>
        </button>
        <?php if ($cloudinaryMLwidgetOprions) : ?>
            <div id="gallery_top_cloudinary_buttons_container">
                <div id="gallery_top_add_from_cloudinary_dd_button"
                    title="<?= $block->escapeHtml(__('Add from Cloudinary')) ?>"
                    data-role="add-from-cloudinary-dd-button"
                    type="button"
                    class="action-secondary add-from-cloudinary-dd-button cloudinary-button-with-logo">
                    <span><?= $block->escapeHtml(__('Add from Cloudinary')) ?></span>
                    <div id="gallery_top_add_from_cloudinary_dd">
                        <div id="gallery_top_add_from_cloudinary_dd_inner">
                            <button id="gallery_top_add_from_cloudinary_button_<?= /* @noEscape*/ $block->getHtmlId() ?>"
                                title="<?= $block->escapeHtml(__('Add Image/Video')) ?>"
                                data-role="add-from-cloudinary-button"
                                type="button"
                                data-mage-init='{"cloudinaryMediaLibraryModal": <?= /* @noEscape*/ $cloudinaryMLwidgetOprions ?>}'
                                class="action-secondary add-from-cloudinary-button">
                                <span><?= $block->escapeHtml(__('Add Image/Video')) ?></span>
                            </button>
                            <button id="gallery_top_add_cldspinset_button_<?= /* @noEscape*/ $block->getHtmlId() ?>"
                                title="<?= $block->escapeHtml(__('Add Spinset')) ?>"
                                data-role="add-cldspinset-button"
                                type="button"
                                data-mage-init='{"cloudinarySpinsetModal": <?= /* @noEscape*/ $cloudinaryMLwidgetOprions ?>}'
                                class="action-secondary">
                                <span><?= $block->escapeHtml(__('Add Spinset')) ?></span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>

<?php
/** @var $block \Magento\Catalog\Block\Adminhtml\Product\Helper\Form\Gallery\Content */
$element = $block->getData('element');
$elementToggleCode = $element->getToggleCode() ? $element->getToggleCode() : 'toggleValueElements(this, this.parentNode.parentNode.parentNode)';
?>

<div id="<?= $block->getHtmlId() ?>"
     class="gallery"
     data-mage-init='{"openVideoModal":{}}'
     data-parent-component="<?= $block->escapeHtml($block->getData('config/parentComponent')) ?>"
     data-images="<?= $block->escapeHtmlAttr($block->getImagesJson()) ?>"
     data-types="<?= $block->escapeHtml($block->jsonSerialize($block->getImageTypes())) ?>">

    <?php if ($cloudinaryMLwidgetOprions) : ?>
        <div id="gallery_inner_add_from_cloudinary_placeholder_button_<?= /* @noEscape*/ $block->getHtmlId() ?>" class="image image-placeholder add-from-cloudinary-button" data-role="add-from-cloudinary-button" data-mage-init='{"cloudinaryMediaLibraryModal": <?= /* @noEscape*/ $cloudinaryMLwidgetOprions ?>}'>
            <div class="product-image-wrapper">
                <p class="image-placeholder-text">
                    <?= $block->escapeHtml(__('Add from Cloudinary')) ?>
                </p>
            </div>
        </div>
    <?php endif; ?>

    <?php
    if (!$block->getElement()->getReadonly()) :
        ?>
        <div class="image image-placeholder">
            <?= /* @noEscape*/ $block->getUploaderHtml() ?>
            <div class="product-image-wrapper">
                <p class="image-placeholder-text">
                    <?= $block->escapeHtml(__('Browse to find or drag image here')) ?>
                </p>
            </div>
        </div>
        <?= /* @noEscape*/ $block->getChildHtml('additional_buttons') ?>
        <?php
    endif;
    ?>
    <?php
    foreach ($block->getImageTypes() as $typeData) :
        ?>
        <input name="<?= $block->escapeHtml($typeData['name']) ?>"
               data-form-part="<?= /* @noEscape*/ $formName ?>"
               class="image-<?= $block->escapeHtml($typeData['code']) ?>"
               type="hidden"
               value="<?= $block->escapeHtml($typeData['value']) ?>"/>
        <?php
    endforeach;
    ?>
    <script id="<?= /* @noEscape*/ $block->getHtmlId() ?>-template" data-template="image" type="text/x-magento-template">
        <div class="image item <% if (data.disabled == 1) { %>hidden-for-front<% } %>  <% if (data.video_url) { %>video-item<% } %>"
             data-role="image">
            <input type="hidden"
                   name="<?= /* @noEscape*/ $elementName ?>[<%- data.file_id %>][position]"
                   value="<%- data.position %>"
                   data-form-part="<?= /* @noEscape*/ $formName ?>"
                   class="position"/>
            <% if (data.media_type !== 'external-video') {%>
            <input type="hidden"
                   name="<?= /* @noEscape*/ $elementName ?>[<%- data.file_id %>][media_type]"
                   data-form-part="<?= /* @noEscape*/ $formName ?>"
                   value="image"/>
            <% } else { %>
            <input type="hidden"
                   name="<?= /* @noEscape*/ $elementName ?>[<%- data.file_id %>][media_type]"
                   value="<%- data.media_type %>"
                   data-form-part="<?= /* @noEscape*/ $formName ?>"/>
            <% } %>
            <input type="hidden"
                   name="<?= /* @noEscape*/ $elementName ?>[<%- data.file_id %>][video_provider]"
                   value="<%- data.video_provider %>"
                   data-form-part="<?= /* @noEscape*/ $formName ?>"/>
            <input type="hidden"
                   name="<?= /* @noEscape*/ $elementName ?>[<%- data.file_id %>][file]"
                   value="<%- data.file %>"
                   data-form-part="<?= /* @noEscape*/ $formName ?>"/>
            <input type="hidden"
                   name="<?= /* @noEscape*/ $elementName ?>[<%- data.file_id %>][value_id]"
                   value="<%- data.value_id %>"
                   data-form-part="<?= /* @noEscape*/ $formName ?>"/>
            <input type="hidden"
                   name="<?= /* @noEscape*/ $elementName ?>[<%- data.file_id %>][label]"
                   value="<%- data.label %>"
                   data-form-part="<?= /* @noEscape*/ $formName ?>"/>
            <input type="hidden"
                   name="<?= /* @noEscape*/ $elementName ?>[<%- data.file_id %>][cldspinset]"
                   value="<%- data.cldspinset %>"
                   data-form-part="<?= /* @noEscape*/ $formName ?>"/>
            <input type="hidden"
                   name="<?= /* @noEscape*/ $elementName ?>[<%- data.file_id %>][disabled]"
                   value="<%- data.disabled %>"
                   data-form-part="<?= /* @noEscape*/ $formName ?>"/>
            <input type="hidden"
                   name="<?= /* @noEscape*/ $elementName ?>[<%- data.file_id %>][removed]"
                   value="" class="is-removed"
                   data-form-part="<?= /* @noEscape*/ $formName ?>"/>
            <input type="hidden"
                   name="<?= /* @noEscape*/ $elementName ?>[<%- data.file_id %>][video_url]"
                   value="<%- data.video_url %>"
                   data-form-part="<?= /* @noEscape*/ $formName ?>"/>
            <input type="hidden"
                   name="<?= /* @noEscape*/ $elementName ?>[<%- data.file_id %>][video_title]"
                   value="<%- data.video_title %>"
                   data-form-part="<?= /* @noEscape*/ $formName ?>"/>
            <input type="hidden"
                   name="<?= /* @noEscape*/ $elementName ?>[<%- data.file_id %>][video_description]"
                   value="<%- data.video_description %>"
                   data-form-part="<?= /* @noEscape*/ $formName ?>"/>
            <input type="hidden"
                   name="<?= /* @noEscape*/ $elementName ?>[<%- data.file_id %>][video_metadata]"
                   value="<%- data.video_metadata %>"
                   data-form-part="<?= /* @noEscape*/ $formName ?>"/>
            <input type="hidden"
                   name="<?= /* @noEscape*/ $elementName ?>[<%- data.file_id %>][role]"
                   value="<%- data.video_description %>"
                   data-form-part="<?= /* @noEscape*/ $formName ?>"/>
            <input type="hidden"
                   name="<?= /* @noEscape*/ $elementName ?>[<%- data.file_id %>][catalog_product_option_type_id]"
                   value="<%- data.catalog_product_option_type_id %>"
                   data-form-part="<?= /* @noEscape*/ $formName ?>"/>
            <input type="hidden"
                   name="<?= /* @noEscape*/ $elementName ?>[<%- data.file_id %>][catalog_product_bundle_selection_id]"
                   value="<%- data.catalog_product_bundle_selection_id %>"
                   data-form-part="<?= /* @noEscape*/ $formName ?>"/>
            <input type="hidden"
                   name="<?= /* @noEscape*/ $elementName ?>[<%- data.file_id %>][tags]"
                   value="<%- data.tags %>"
                   data-form-part="<?= /* @noEscape*/ $formName ?>"/>
            <input type="hidden"
                   name="<?= /* @noEscape*/ $elementName ?>[<%- data.file_id %>][ui_role]"
                   value="<%- data.ui_role %>"
                   data-form-part="<?= /* @noEscape*/ $formName ?>"/>

            <div class="product-image-wrapper <% if (data.cldspinset) { %>cldspinset-overlay<% } %>">
                <img class="product-image"
                     data-role="image-element"
                     src="<%- data.url %>"
                     alt="<%- data.label %>"/>

                <div class="actions">
                    <button type="button"
                            class="action-remove"
                            data-role="delete-button"
                            title="<% if (data.media_type == 'external-video') {%>
                                <?= $block->escapeHtml(__('Delete video')) ?>
                            <%} else {%>
                                <?= $block->escapeHtml(__('Delete image')) ?>
                            <%}%>">
                    <span>
                        <% if (data.media_type == 'external-video') { %>
                        <?= $block->escapeHtml(__('Delete video')) ?>
                        <% } else {%>
                        <?= $block->escapeHtml(__('Delete image')) ?>
                        <%} %>
                    </span>
                    </button>
                    <div class="draggable-handle"></div>
                </div>
                <div class="image-fade"><span><?= $block->escapeHtml(__('Hidden')) ?></span></div>
            </div>

            <div class="item-description">
                <% if (data.media_type !== 'external-video') {%>
                <div class="item-title" data-role="img-title"><%- data.label %></div>
                <div class="item-size">
                    <span data-role="image-dimens"></span>, <span data-role="image-size"><%- data.sizeLabel %></span>
                </div>
                <% } else { %>
                <div class="item-title" data-role="img-title"><%- data.video_title %></div>
                <% } %>
            </div>

            <ul class="item-roles" data-role="roles-labels">
                <?php
                foreach ($block->getImageTypes() as $typeData) :
                    ?>
                    <li data-role-code="<?= $block->escapeHtml($typeData['code']) ?>" class="item-role item-role-<?= $block->escapeHtml($typeData['code']) ?>">
                        <?= $block->escapeHtml($typeData['label']) ?>
                    </li>
                    <?php
                endforeach;
                ?>
            </ul>
        </div>
    </script>

    <script data-role="img-dialog-container-tmpl" type="text/x-magento-template">
        <div class="image-panel" data-role="dialog">
        </div>
    </script>

    <script data-role="img-dialog-tmpl" type="text/x-magento-template">
        <div class="image-panel-preview">
            <img src="<%- data.url %>" alt="<%- data.label %>" />
        </div>
        <div class="image-panel-controls">
            <strong class="image-name"><%- data.label %></strong>

            <fieldset class="admin__fieldset fieldset-image-panel">
                <div class="admin__field field-image-description">
                    <label class="admin__field-label" for="image-description">
                        <span><?= /* @noEscape*/ __('Alt Text') ?></span>
                    </label>

                    <div class="admin__field-control">
                            <textarea data-role="image-description"
                                      rows="3"
                                      class="admin__control-textarea"
                                      name="<?= /* @noEscape*/ $elementName ?>[<%- data.file_id %>][label]"><%- data.label %></textarea>
                    </div>
                </div>

                <div class="admin__field field-image-cldspinset">
                    <label class="admin__field-label" for="image-cldspinset">
                        <span><?= /* @noEscape*/ __('Cloudinary Spinset Tag') ?></span>
                    </label>

                    <div class="admin__field-control">
                            <input data-role="image-cldspinset"
                                    class="admin__control-text"
                                    name="<?= /* @noEscape*/ $elementName ?>[<%- data.file_id %>][cldspinset]"
                                    value="<%- data.cldspinset %>" />
                    </div>
                </div>

                <div class="admin__field field-image-role">
                    <label class="admin__field-label">
                            <span><?= $block->escapeHtml(__('Role')) ?></span>
                    </label>
                    <div class="admin__field-control">
                        <ul class="multiselect-alt">
                            <?php
                            foreach ($block->getMediaAttributes() as $attribute) :
                                ?>
                                <li class="item">
                                    <label>
                                        <input class="image-type"
                                               data-role="type-selector"
                                               data-form-part="<?= /* @noEscape*/ $formName ?>"
                                               type="checkbox"
                                               value="<?= $block->escapeHtml($attribute->getAttributeCode()) ?>"
                                        />
                                        <?= /* @noEscape*/ $block->escapeHtml($attribute->getFrontendLabel()) ?>
                                    </label>
                                </li>
                                <?php
                            endforeach;
                            ?>
                        </ul>
                    </div>
                </div>

                <div class="admin__field field-image-product-option-types">
                    <label class="admin__field-label">
                        <span><?= $block->escapeHtml(__('Product option type')) ?></span>
                    </label>

                    <div class="admin__field-control">
                        <ul class="multiselect-alt">
                            <?php
                            foreach ($block->getProductOptionTypes() as $optionType) :
                                ?>
                                <li class="item">
                                    <label>
                                        <input class="image-option-selector"
                                               data-role="option-selector"
                                               data-form-part="<?= /* @noEscape*/ $formName ?>"
                                               type="checkbox"
                                               value="<?= $block->escapeHtml($optionType['id']) ?>"
                                        />
                                        <?= /* @noEscape*/ $block->escapeHtml($optionType['label']) ?>
                                    </label>
                                </li>
                                <?php
                            endforeach;
                            ?>
                        </ul>
                    </div>
                </div>

                <div class="admin__field field-image-product-ui-role">
                    <label class="admin__field-label">
                        <span><?= $block->escapeHtml(__('Image UI Role')) ?></span>
                    </label>

                    <div class="admin__field-control">
                        <ul class="multiselect-alt">
                            <?php
                            foreach ($block->getUiRoles() as $uiRole) :
                                ?>
                                <li class="item">
                                    <label>
                                        <input class="image-option-selector"
                                               data-role="ui-selector"
                                               data-form-part="<?= /* @noEscape*/ $formName ?>"
                                               type="checkbox"
                                               value="<?= $block->escapeHtml($uiRole) ?>"
                                        />
                                        <?= /* @noEscape*/ $block->escapeHtml($uiRole) ?>
                                    </label>
                                </li>
                            <?php
                            endforeach;
                            ?>
                        </ul>
                    </div>
                </div>

                <div class="admin__field field-image-product-bundle-selections">
                    <label class="admin__field-label">
                        <span><?= $block->escapeHtml(__('Product bundle selections')) ?></span>
                    </label>

                    <div class="admin__field-control">
                        <ul class="multiselect-alt">
                            <?php
                            foreach ($block->getProductBundleSelections() as $selection) :
                                ?>
                                <li class="item">
                                    <label>
                                        <input class="image-option-selector"
                                               data-role="bundle-selector"
                                               data-form-part="<?= /* @noEscape*/ $formName ?>"
                                               type="checkbox"
                                               value="<?= $block->escapeHtml($selection['id']) ?>"
                                        />
                                        <?= /* @noEscape*/ $block->escapeHtml($selection['label']) ?>
                                    </label>
                                </li>
                                <?php
                            endforeach;
                            ?>
                        </ul>
                    </div>
                </div>

                <div class="admin__field field-image-tags">
                    <label class="admin__field-label" for="image-tags">
                        <span><?= /* @noEscape*/ __('Tags') ?></span>
                    </label>

                    <div class="admin__field-control">
                        <input data-role="image-tags"
                               class="admin__control-text"
                               name="<?= /* @noEscape*/ $elementName ?>[<%- data.file_id %>][tags]"
                               value="<%- data.tags %>" />
                    </div>
                </div>

                <div class="admin__field admin__field-inline field-image-size" data-role="size">
                    <label class="admin__field-label">
                        <span><?= /* @noEscape*/ __('Image Size') ?></span>
                    </label>
                    <div class="admin__field-value" data-message="<?= /* @noEscape*/ __('{size}') ?>"></div>
                </div>

                <div class="admin__field admin__field-inline field-image-resolution" data-role="resolution">
                    <label class="admin__field-label">
                        <span><?= /* @noEscape*/ __('Image Resolution') ?></span>
                    </label>
                    <div class="admin__field-value" data-message="<?= /* @noEscape*/ __('{width}^{height} px') ?>"></div>
                </div>

                <div class="admin__field field-image-hide">
                    <div class="admin__field-control">
                        <div class="admin__field admin__field-option">
                            <input type="checkbox"
                                   id="hide-from-product-page"
                                   data-role="visibility-trigger"
                                   data-form-part="<?= /* @noEscape*/ $formName ?>"
                                   value="1"
                                   class="admin__control-checkbox"
                                   name="<?= /* @noEscape*/ $elementName ?>[<%- data.file_id %>][disabled]"
                            <% if (data.disabled == 1) { %>checked="checked"<% } %> />

                            <label for="hide-from-product-page" class="admin__field-label">
                                <?= $block->escapeHtml(__('Hide from Product Page')) ?>
                            </label>
                        </div>
                    </div>
                </div>
            </fieldset>
        </div>
    </script>
    <div id="<?= /* @noEscape */ $block->getNewVideoBlockName() ?>" style="display:none">
        <?= /* @noEscape*/ $block->getFormHtml() ?>
        <div id="video-player-preview-location" class="video-player-sidebar">
            <div class="video-player-container"></div>
            <div class="video-information title">
                <label><?= $block->escapeHtml(__('Title:')) ?> </label><span></span>
            </div>
            <div class="video-information uploaded">
                <label><?= $block->escapeHtml(__('Uploaded:')) ?> </label><span></span>
            </div>
            <div class="video-information uploader">
                <label><?= $block->escapeHtml(__('Uploader:')) ?> </label><span></span>
            </div>
            <div class="video-information duration">
                <label><?= $block->escapeHtml(__('Duration:')) ?> </label><span></span>
            </div>
        </div>
    </div>

    <?= $block->getChildHtml('new-video') ?>

    <div id="cldspinset-modal" style="display:none">
        <div id="cldspinset-preview-location" class="cldspinset-sidebar">
            <div class="cldspinset-form-container">
                <fieldset class="admin__fieldset fieldset-image-panel">
                    <div class="admin__field field-image-cldspinset">
                        <label class="admin__field-label" for="image-cldspinset">
                            <span><?= /* @noEscape*/ __('Cloudinary Spinset Tag') ?></span>
                        </label>
                        <div class="admin__field-control">
                            <input data-role="new-cldspinset"
                                class="admin__control-text"
                                name="new_cldspinset"
                                value="" />
                        </div>
                    </div>
                </fieldset>
            </div>
            <div class="cldspinset-preview-container">
                <fieldset class="admin__fieldset fieldset-image-panel">
                    <div class="admin__field field-image-cldspinset">
                        <label class="admin__field-label" for="image-cldspinset">
                            <span><?= /* @noEscape*/ __('Preview') ?></span>
                        </label>
                        <div class="admin__field-control">
                            <div id="cldspinset-preview" class="cldspinset-preview">
                                <img id="cldspinset-preview-img" class="placeholder" src="<?= /* @noEscape*/ $block->getViewFileUrl('Cloudinary_Cloudinary::images/cloudinary_spinset_placeholder.svg') ?>" alt="Cloudinary spinset preview" data-placeholder="<?= /* @noEscape*/ $block->getViewFileUrl('Cloudinary_Cloudinary::images/cloudinary_spinset_placeholder.svg') ?>"/>
                                <div id="cldspinset-indic"></div>
                            </div>
                        </div>
                    </div>
                </fieldset>
            </div>
        </div>
    </div>

</div>
<script>
    jQuery('body').trigger('contentUpdated');
</script>
