<?php

use ForeverCompanies\CustomSales\Block\Adminhtml\Order\View\LoggedUser;
use Magento\Framework\Exception\LocalizedException;

/** @var LoggedUser $block */
?>
<?php
if ($block->getOrderStatus() == 'quote') {
    ?>
    <div class="admin__page-section-title">
        <span><?= $block->escapeHtml('Expiration Date: ' . $block->getOrderExpirationDate()) ?></span>
    </div> <?php
}
?>
<div class="admin__page-section-title">
    <span class="title"><?= $block->escapeHtml('Logged User: ' . $block->getLoggedUser()) ?></span>
</div>
<div class="admin__page-section-title">
    <span class="title"><?= $block->escapeHtml('Sales Person: ' . $block->getSalesPerson()) ?></span>
</div>
