<?php

use ForeverCompanies\CustomSales\Block\Adminhtml\Order\View\SalesPerson;
use Magento\Framework\Exception\LocalizedException;
use Magento\Framework\Escaper;

/** @var SalesPerson $block */
/** @var $escaper Escaper */

$legacyDispatchDate = $block->getLegacyDispatchDate();
$legacyDeliveryDate = $block->getLegacyDeliveryDate();

?>

<?php if (strlen($legacyDispatchDate) > 0): ?>
    <table class="admin__table-secondary order-account-information-table">
        <tbody>
        <tr>
            <th>Ship Date (legacy)</th>
            <td><?php try {
                    echo $escaper->escapeHtml($legacyDispatchDate);
                } catch (LocalizedException $e) {
                    echo '';
                } ?></td>
        </tr>
        </tbody>
    </table>
<?php endif; ?>

<?php if (strlen($legacyDispatchDate) > 0): ?>
<table class="admin__table-secondary order-account-information-table">
    <tbody>
    <tr>
        <th>Delivery Date (legacy)</th>
        <td><?php try {
                echo $escaper->escapeHtml($legacyDeliveryDate);
            } catch (LocalizedException $e) {
                echo '';
            } ?></td>
    </tr>
    </tbody>
</table>
<?php endif; ?>

<table class="admin__table-secondary order-account-information-table">
    <tbody>
    <tr>
        <th>Sales Person</th>
        <td><?php try {
                echo $escaper->escapeHtml($block->getSalesPerson());
            } catch (LocalizedException $e) {
                echo '';
            } ?></td>
    </tr>
    </tbody>
</table>
<form style="display: inline-table" action="<?= $escaper->escapeUrl($block->getExchangeUrl()) ?>" method="post"
      id="order-create-change-salesperson-form">
    <label class="checkbox"> Is Exchange
        <input type="checkbox" name="is_exchange" id="is_exchange"
               value="1"
            <?php if ($block->getIsExchange()) { ?>
               checked="checked" class="checkbox"/>
        <?php } ?>
    </label>
    <input type="submit" value="Save change" id="order-view-add-warranty">
    <input name="form_key" type="hidden" value="<?= $escaper->escapeHtml($block->getFormKey()) ?>">
    <input name="order_id" type="hidden" value="<?php try {
        echo $escaper->escapeHtml($block->getOrder()->getId());
                                                } catch (LocalizedException $e) {
                                                    echo '';
                                                } ?>">
</form>
