<?php

/** @var EditOrder $block */

use Mageplaza\EditOrder\Block\Adminhtml\Order\EditOrder;

$order = $block->getCurrentOrder();
?>

<?php if ($order->getStatus() === 'quote') : ?>
    <form id="edit_form" data-order-config='<?= $block->escapeHtml($block->getOrderDataJson()) ?>'
          data-load-base-url="<?= /* @noEscape */ $block->getLoadBlockUrl() ?>"
          action="<?= /* @noEscape */ $block->getActionForm() ?>" method="post" enctype="multipart/form-data"
          data-mage-init='{"validation":{}}'>
        <div id="order-data">
            <div id="order-message">
                <?= $block->getChildHtml('message') ?>
            </div>
            <?= $block->getChildHtml('mpeditorder_edit_order_info') ?>
            <?= $block->getChildHtml('mpeditorder_edit_account_info') ?>
            <?= $block->getChildHtml('mpeditorder_edit_billing_address') ?>
            <?php if ($block->isVirtualProduct()) : ?>
                <?= $block->getChildHtml('mpeditorder_edit_shipping_address') ?>
            <?php endif ?>
            <?= $block->getChildHtml('mpeditorder_edit_payment_method') ?>
            <?= $block->getChildHtml('mpeditorder_edit_shipping_method') ?>
            <?= $block->getChildHtml('mpeditorder_edit_items') ?>
            <?= $block->getChildHtml('mpeditorder_quick_edit') ?>
        </div>
    </form>
    <style>
        .order-account-information .actions, .order-billing-address .actions, .order-shipping-address .actions {
            display: none;
        }
    </style>
<?php endif ?>
