<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer\Actions\Remove */
?>
<?php if($block->isRingBuilderSet()): ?>
    <a href="#"
       title="<?= $block->escapeHtml(__('Rebuild Ring')) ?>"
       class="action action-delete"
       data-post='<?= /* @noEscape */ $block->getRebuildPostJson() ?>'>
        <span>
            <?= $block->escapeHtml(__('Rebuild Ring')) ?>
        </span>
    </a>
<?php endif; ?>

<a href="#"
   title="<?= $block->escapeHtml(__('Remove item')) ?>"
   class="action action-delete"
   data-post='<?= /* @noEscape */ $block->getDeletePostJson() ?>'>
    <span>
        <?= $block->escapeHtml(__('Remove item')) ?>
    </span>
</a>
