<?php
/** @var $block ForeverCompanies\Salesforce\Block\System\Config\Form\Button\Button */
?>
<div class="actions button-container">
    <a href="<?php /* @escapeNotVerified */ echo $block->escapeUrl($block->getButtonUrl()) ?>">
        <button  class="button action-configure"
                 type="button"
                 data-role="<?php /* @escapeNotVerified */ echo $block->getHtmlId() ?>"
                 id="<?php /* @escapeNotVerified */ echo $block->getHtmlId() ?>" disabled="disabled">
            <span><?php /* @escapeNotVerified */ echo $block->escapeHtml($block->getButtonLabel()) ?></span>
        </button>
    </a>
</div>
