<script>
    require([
        "jquery",
        "getSalesFields",
        "domReady!"
    ], function ($, Fields) {
        var fields = new Fields({url: '<?php echo $this->getUpdateUrl(); ?>'});
        $("button[data-ui-id='salesforce-map-edit-updateallfields-button']").click(
            function() {
                var url = '<?php echo $this->getUpdateAllFields() ?>';
                jQuery.ajax({
                    type: 'POST',
                    url: url,
                    data: {
                        form_key: FORM_KEY
                    },
                    showLoader: true,
                    success: function(){
                        alert('Update success');
                    }
                });
            });
        });
</script>
